### ISSUE TITLE
This copy request is illegal because it is trying to copy an object to itself without changing the object's metadata, storage class, website redirect location or encryption attributes.

### ISSUE THREAD

**Issue by zlp886** [afterlogic/dav#1]
when use aws S3 
same folder copy and paste 

get this error

This copy request is illegal because it is trying to copy an object to itself without changing the object's metadata, storage class, website redirect location or encryption attributes.

so i modify function 
public function copyObjectTo($sToStorage, $sToPath, $sNewName, $bMove = false, $aUpdateMetadata = null){}

https://github.com/afterlogic/dav/blob/master/lib/DAV/FS/S3/NodeTrait.php#L102

add  4 rows 

if($sFullFromPath === $sFullToPath){
	$sNewName = ('new_' . time() . '_' . $sNewName);
	$sFullToPath = $this->getPathForS3($sToStorage . \rtrim($sToPath, '/') . '/' . $sNewName . ($this->isDirectoryObject() ? '/' : ''));
}	

can help me solve error

**Comment by afterlogic-support** [comment]
Thank you. Developers have confirmed the issue and [provided a fix](https://github.com/afterlogic/aurora-module-s3-filestorage/commit/006d2231b895ef78f1aa87277511f6002e4b1868) for it, it'll be included into the next version of course.

**Comment by zlp886** [comment]
Thank you
